spring.application.name=dryforest
spring.flyway.enabled=false
server.port=8081

spring.datasource.url=jdbc:postgresql://voahary:y4lTdfLMrP3X9Hs6qtsHZYScOwq03LdC@dpg-d8gm4etckfvc73cs6q8g-a/dryforest
# spring.datasource.url=jdbc:postgresql://dpg-d8gm4etckfvc73cs6q8g-a.frankfurt-postgres.render.com:5432/dryforest
# spring.datasource.url=jdbc:postgresql://localhost:5432/dryforest

# spring.datasource.username=postgres
spring.datasource.username=voahary
# spring.datasource.password=post
spring.datasource.password=y4lTdfLMrP3X9Hs6qtsHZYScOwq03LdC

spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=+31flreDydoQAELprT1653k0PR/cp3ZT2DL0FpCQDuHrHBby1GIDLivRsjp7eM4kLe64U7+BBnaTM+GS886lGQ==
jwt.expiration.ms=86400000

sync.pullable-tables-patrol=patrol_group,incident_patrol_type,observation_patrol_type,category_animal,animal
sync.pullable-tables-reforestation=role,person,species_type,species,severity,type_zone,patrol_group,category_animal,animal
